/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client.view;

import client.controller.Client;
import client.model.CirclePanel;
import client.model.OvalPanel;
import client.model.User;
import client.model.WheatAndRice;
import java.awt.Color;
import java.awt.Container;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

/**
 *
 * @author quang
 */
public class GameFrm extends javax.swing.JFrame {

    ArrayList<WheatAndRice> grains = new ArrayList<>();
    private OvalPanel newOvalPanel;
    private CirclePanel newWheatPanel;
    private CirclePanel newRicePanel;
    private Timer timer;
    private User DoiThu;
    private Integer second, minute;
    private Boolean isDone;
    private int diemDoithu;

    public GameFrm(User competitor, int room_ID, int isStart, OvalPanel neww) {
        initComponents();
        this.setTitle("Game");
        this.setResizable(false);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setLayout(null);

        this.isDone = false;
        this.DoiThu = competitor;
        this.getContentPane().setBackground(new Color(240, 240, 240));
        lblName.setText(Client.user.getNickname());
        lblDoiThu.setText(DoiThu.getNickname());

        // Oval
        int x_Oval = PanelOval.getX();
        int y_Oval = PanelOval.getY();
        int ovalWidth = PanelOval.getWidth();
        int ovalHeight = PanelOval.getHeight();

        Container parent = PanelOval.getParent();
        parent.remove(PanelOval);

        newOvalPanel = neww;
        System.out.println("/////");
        for (int i = 0; i < newOvalPanel.getGrains().size(); i++) {
            System.out.println(newOvalPanel.getGrains().get(i).getX() + " " + newOvalPanel.getGrains().get(i).getY());
        }
        newOvalPanel.setBounds(x_Oval, y_Oval, ovalWidth, ovalHeight);

        parent.add(newOvalPanel);
        // Circle Wheat
        int x_Wheat = PanelWheat.getX();
        int y_Wheat = PanelWheat.getY();
        int radius_Wheat = PanelWheat.getWidth();
        parent.remove(PanelWheat);

        newWheatPanel = new CirclePanel(radius_Wheat);
        newWheatPanel.setBounds(x_Wheat, y_Wheat, radius_Wheat, radius_Wheat);

        parent.add(newWheatPanel);

        // Circle Rice
        int x_Rice = PanelRice.getX();
        int y_Rice = PanelRice.getY();
        int radius_Rice = PanelRice.getWidth();
        parent.remove(PanelRice);

        newRicePanel = new CirclePanel(radius_Rice);
        newRicePanel.setBounds(x_Rice, y_Rice, radius_Rice, radius_Rice);

        parent.add(newRicePanel);

        parent.revalidate();
        parent.repaint();

        //Setup timer
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String temp = minute.toString();
                String temp1 = second.toString();
                if (temp.length() == 1) {
                    temp = "0" + temp;
                }
                if (temp1.length() == 1) {
                    temp1 = "0" + temp1;
                }
                if (second == 0) {
                    lblTime.setText(temp + ":" + temp1);
                    JOptionPane.showMessageDialog(rootPane, "Hết giờ");
                    ActionEvent evt = new ActionEvent(btnDone, ActionEvent.ACTION_PERFORMED, null);
                    btnDoneActionPerformed(evt);
                } else {
                    lblTime.setText(temp + ":" + temp1);
                    second--;
                }

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        PanelOval = new javax.swing.JPanel();
        PanelWheat = new javax.swing.JPanel();
        btnDone = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblDoiThu = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        PanelRice = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelOval.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout PanelOvalLayout = new javax.swing.GroupLayout(PanelOval);
        PanelOval.setLayout(PanelOvalLayout);
        PanelOvalLayout.setHorizontalGroup(
            PanelOvalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );
        PanelOvalLayout.setVerticalGroup(
            PanelOvalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        PanelWheat.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout PanelWheatLayout = new javax.swing.GroupLayout(PanelWheat);
        PanelWheat.setLayout(PanelWheatLayout);
        PanelWheatLayout.setHorizontalGroup(
            PanelWheatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        PanelWheatLayout.setVerticalGroup(
            PanelWheatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );

        btnDone.setBackground(new java.awt.Color(153, 153, 153));
        btnDone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDone.setForeground(new java.awt.Color(255, 255, 255));
        btnDone.setText("Xong");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bạn");

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(102, 255, 255));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("{Nickname}");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblName))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Đối thủ");

        lblDoiThu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDoiThu.setForeground(new java.awt.Color(255, 51, 51));
        lblDoiThu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoiThu.setText("{Nickname}");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDoiThu, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblDoiThu))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        lblTime.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime.setText("00:00");

        PanelRice.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout PanelRiceLayout = new javax.swing.GroupLayout(PanelRice);
        PanelRice.setLayout(PanelRiceLayout);
        PanelRiceLayout.setHorizontalGroup(
            PanelRiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        PanelRiceLayout.setVerticalGroup(
            PanelRiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Thóc");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Gạo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(PanelWheat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addComponent(btnDone)
                        .addGap(126, 126, 126)
                        .addComponent(PanelRice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(PanelOval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(5, 5, 5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(PanelOval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnDone))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PanelWheat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelRice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        try {
            this.isDone = true;
            stopTimer();
            Client.socketHandle.write("done," + tongDiem());
        } catch (IOException ex) {
            Logger.getLogger(GameFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDoneActionPerformed
    public void chuaXong() {
        try {
            Client.socketHandle.write("chua-xong,");
        } catch (IOException ex) {
            Logger.getLogger(GameFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void guiKQ(String rs) {
        try {
            Client.socketHandle.write("gui-ket-qua," + rs);
        } catch (IOException ex) {
            Logger.getLogger(GameFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void stopTimer() {
        timer.stop();
    }

    public void startTimer() {
        second = 60;
        minute = 0;
        timer.start();
    }

    public void newgame() {
        startTimer();
    }

    public int tongDiem() {
        int sum = 0;
        for (int i = 0; i < newWheatPanel.getGrains().size(); i++) {
            if (newWheatPanel.getGrains().get(i).getColor().equals(new Color(255, 204, 0))) {
                sum += 1;
            } else {
                sum -= 1;
            }
        }
        for (int i = 0; i < newRicePanel.getGrains().size(); i++) {
            if (newRicePanel.getGrains().get(i).getColor().equals(new Color(255, 255, 255))) {
                sum += 1;
            } else {
                sum -= 1;
            }
        }
        if (sum < 0) {
            sum = 0;
        }
        return sum;
    }

    public void ketQua(String result) {
        if (result.equals("win")) {

            String message = "Bạn Thắng\nĐiểm bạn là: " + tongDiem() + "\nĐiểm đối thủ là: " + getDiemDoithu();
            JOptionPane.showMessageDialog(rootPane, message);
            try {
                Client.socketHandle.write("win," + tongDiem() + "," + getDiemDoithu());
            } catch (IOException ex) {
                Logger.getLogger(GameFrm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (result.equals("draw")) {
            String message = "Hoà\nĐiểm bạn là: " + tongDiem() + "\nĐiểm đối thủ là: " + getDiemDoithu();
            JOptionPane.showMessageDialog(rootPane, message);
            try {
                Client.socketHandle.write("draw," + tongDiem() + "," + getDiemDoithu());
            } catch (IOException ex) {
                Logger.getLogger(GameFrm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            String message = "Bạn Thua\nĐiểm bạn là: " + tongDiem() + "\nĐiểm đối thủ là: " + getDiemDoithu();
            JOptionPane.showMessageDialog(rootPane, message);
            try {
                Client.socketHandle.write("lose," + tongDiem() + "," + getDiemDoithu());
            } catch (IOException ex) {
                Logger.getLogger(GameFrm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    /**
     * @param args the command line arguments
     */
    public Boolean getIsDone() {
        return isDone;
    }

    public int getDiemDoithu() {
        return diemDoithu;
    }

    public void setDiemDoithu(int diemDoithu) {
        this.diemDoithu = diemDoithu;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelOval;
    private javax.swing.JPanel PanelRice;
    private javax.swing.JPanel PanelWheat;
    private javax.swing.JButton btnDone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblDoiThu;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTime;
    // End of variables declaration//GEN-END:variables
}
